### ISSUE TITLE
Seeder error: update cannot add or update a child row a foreign key constraint fails

### ISSUE THREAD

**Issue by JordyLock** [davinci-ao/mbw-cijfers#17]
Seeder can't execute and gives the error: update cannot add or update a child row a foreign key constraint fails

**To Reproduce**
1. go to cmd
2. enter : 'php artisan db:seed'
3. See error

**Expected behavior**
Go to cmd, enter: 'php artisan db:seed' and let the seeder run succesfully.

**Comment by JordyLock** [comment]
Issue fixed in Merqe request #18

**Comment by DennisVBlanken** [comment]
Thank You, Very Cool.
